# If you define PETSC_DIR and PETSC_ARCH, this should be enough to compile
# anything named ex#.c, where # is a 1+ digit number.

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
